version: '3.8'

services:
  nginx:
    image: nginx:latest
    # volumes: 
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "frontend"
      - "backend"
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
  frontend:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=/api/
      - CHOKIDAR_USEPOLLING=true
    container_name: bloglist-frontend
  backend:
    image: bloglist-backend
    build:
      context: ./bloglist-backend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: bloglist-backend